<a href="https://colab.research.google.com/github/pbeens/ICS-Computer-Studies/blob/master/Coursera_Introduction_to_Data_Science_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

Outline: https://www.coursera.org/learn/python-data-analysis/home/week/1

Forum: https://www.coursera.org/learn/python-data-analysis/discussions/weeks/1

## Introduction to Specialization

Video: https://www.coursera.org/learn/python-data-analysis/lecture/TPrDp/introduction-to-specialization

- Basic Python
- Pandas
- Advanced Querying and Manipulation
- Basic statistical analysis

## Introduction to the Course

Video: https://www.coursera.org/learn/python-data-analysis/lecture/MIvLe/introduction-to-the-course

- Data manipulation
- Pandas library, defacto standard
- Tutorial-style videos, using Jupyter
- Strategy for learning: take your own notes using Jupyter

## Syllabus

Link: https://www.coursera.org/learn/python-data-analysis/supplement/DNjE6/syllabus

- Prerequisites
- Grading and assignments
- Code of Conduct
- Working offline
- Accessibility
- Help!

## Notice for Auditing Learners: Assignment Submission

Can't submit assignments unless you are a verified (paid?) learner. A link is available to pursue this path.

## The Coursera Jupyter Notebook System

Video: https://www.coursera.org/learn/python-data-analysis/lecture/nWh1K/the-coursera-jupyter-notebook-system

- code cells and markdown cells
- code cells retain what they did in previous cells.
- Kernal/Runtime > Interrupt to stop a running process or infinite loop


## Your Personal Jupyter Notebook Workspace

Link: https://www.coursera.org/learn/python-data-analysis/ungradedLab/33VUU/your-personal-jupyter-notebook-workspace

## Week 1 Textbook Reading Assignment

Link: https://www.coursera.org/learn/python-data-analysis/supplement/fP74v/week-1-textbook-reading-assignment

- Chapter Two: Python Language Basics, IPython, and Jupyter Notebooks
- Chapter Three: Built-In Data Structures, Functions, and Files
- Chapter 4: NumPy Basics: Arrays and Vectorized Computation
- Appendix A: Advanced NumPy (optional)

### Magic Commands

In [1]:
# Jupyter has magic commands!
import numpy as np
%timeit a = np.random.randn(100, 100)

# magic commands can be assigned to variables
foo = %pwd
print(f'pwd: {foo}')

1000 loops, best of 5: 418 µs per loop
pwd: /content


- %quickref
- %magic
- %debug
- %hist
%pdb
%paste
%cpaste
%reset
%page OBJECT %run script.py %prun statement %time statement %timeit statement
%who, %who_ls, %whos 
%xdel variable


In [2]:
# May be useful later...
%matplotlib inline

## 50 years of Data Science, David Donoho (Optional)

Link: http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf

## Python Functions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/v7PKy/python-functions

High-level, interpretted language. Often used interactively, especially in Jupyter. Dynamically-typed, meaning variables are not declared as a specific type. 

Jupyter is stateful, meaning it retains values run in previous cells. 

A function returns None if not specified. 

### Examples Demo'd

In [3]:
x = 1
y = 2
x + y

3

In [4]:
x

1

In [5]:
# a function, with optional 3rd parameter
def add_numbers(x, y, z=None):
  if (z == None):
    return x + y
  else:
    return x + y + z

print(add_numbers(2, 4, 2))
print(add_numbers(2, 4))

8
6


## Python Types and Sequences

Video: https://www.coursera.org/learn/python-data-analysis/lecture/fZ466/python-types-and-sequences

`type()` shows which type a variable is

Tuple is immutable (cannot be changed). Created with parentheses. 

Lists are mutable and created with brackets. `append()` lets you add items to the list.

Lists and tuples are iterable types, typically using a `for` loop. Can be accessed via an index. Can be accessed via slicing. 

In [6]:
x = (1, 'a', 2, 'b')
print(type(x))
x = [1, 'a', 2, 'b']
print(type(x))
x.append(3.3)
print(x)
for item in x:
  print(item)
print(len(x))
print('a' in x)
print(x[0], x[0:1], x[0:2], x[:2], x[-2:])

<class 'tuple'>
<class 'list'>
[1, 'a', 2, 'b', 3.3]
1
a
2
b
3.3
5
True
1 [1] [1, 'a'] [1, 'a'] ['b', 3.3]


Strings can be split:

In [7]:
items = 'A B C D'.split()
print(items)

['A', 'B', 'C', 'D']


Dictionaries

In [8]:
# example from https://www.w3schools.com/python/python_dictionaries.asp
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for spec, data in thisdict.items():
  print(spec, data)

brand Ford
model Mustang
year 1964


In [9]:
for data in thisdict.values():
  print(data)

Ford
Mustang
1964


In [10]:
for key in thisdict.keys():
  print(key)

brand
model
year


Multiple assignments can be done at once.

In [11]:
a, b, c = 1, "abc", [4, 5]
print(a)
print(b)
print(c)

1
abc
[4, 5]


## Python More on Strings

Video: https://www.coursera.org/learn/python-data-analysis/lecture/HPh3O/python-more-on-strings

Strings are Unicode-based. They used to be based on ASCII which was too limited. UTF solves this problem by allowing over a million characters. 

Python allows placeholders for variables when concatenating strings. The video covers `format()` but we can now use f-strings.

## Python Demonstration: Reading and Writing CSV files

Video: https://www.coursera.org/learn/python-data-analysis/lecture/ktRTE/python-demonstration-reading-and-writing-csv-files



In [12]:
# This block will let you upload a file from your local computer.
# Instead, we will clone a GitHub repository, in the next cell.
import csv
# mpg.csv
from google.colab import files
# uploaded = files.upload() # Use GitHub clone instead!

In [13]:
!git clone https://github.com/pbeens/Coursera-Introduction-to-Data-Science-with-Python.git

Cloning into 'Coursera-Introduction-to-Data-Science-with-Python'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 117 (delta 20), reused 42 (delta 9), pack-reused 0
Receiving objects: 100% (117/117), 11.65 MiB | 11.02 MiB/s, done.
Resolving deltas: 100% (20/20), done.


In [14]:
# Testing another way to get a file from online
import urllib.request
url = 'https://gist.githubusercontent.com/pbeens/09530d2a47a926940216b971ecdce369/raw/50f899381a90c94cfd130dc41599fb3d51a2d372/mpg.csv'
urllib.request.urlretrieve(url, "mpg.csv")

('mpg.csv', <http.client.HTTPMessage at 0x7f9fa2e69210>)

In [15]:
import csv

%precision 2 # not working in this cell for some reason
mpg_file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/datasets/mpg.csv'
with open(mpg_file) as csvfile:
  mpg = list(csv.DictReader(csvfile))

# let's look at the first entry
print(mpg[:1])

# how many entries?
print(len(mpg))

# the keys
print(mpg[0].keys())

# avg mpg, city and highway
cty_mpg_avg = sum(float(d['cty']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{cty_mpg_avg:.2f}') # Note: %precision 2 did not work 
hwy_mpg_avg = sum(float(d['hwy']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{hwy_mpg_avg:.2f}')

# cylinder mpg study
cylinders = set(d['cyl'] for d in mpg) # create set of # of cylinders
print(cylinders)

cty_mpg_by_cyl = []
for c in cylinders:
  sum_mpg = 0
  cyl_type_count = 0
  for d in mpg:
    if d['cyl'] == c:
      sum_mpg += float(d['cty'])
      cyl_type_count += 1
  cty_mpg_by_cyl.append((c, round(sum_mpg / cyl_type_count, 2)))
print(sorted(cty_mpg_by_cyl))

# vehicle class study
vehicle_classes = set(d['class'] for d in mpg)
print(vehicle_classes)

hwy_mpg_by_class = []
for vc in vehicle_classes:
  sum_mpg = 0
  vehicle_class_count = 0
  for d in mpg:
    if d['class'] == vc:
      sum_mpg += float(d['hwy'])
      vehicle_class_count += 1
  hwy_mpg_by_class.append((vc, round(sum_mpg / vehicle_class_count)))
print(sorted(hwy_mpg_by_class))


[OrderedDict([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])]
234
odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])
16.86
23.44
{'8', '5', '6', '4'}
[('4', 21.01), ('5', 20.5), ('6', 16.22), ('8', 12.57)]
{'minivan', 'suv', 'compact', 'subcompact', 'midsize', 'pickup', '2seater'}
[('2seater', 25), ('compact', 28), ('midsize', 27), ('minivan', 22), ('pickup', 17), ('subcompact', 28), ('suv', 18)]


## Python Dates and Times

Video: https://www.coursera.org/learn/python-data-analysis/lecture/Fpybh/python-dates-and-times

Dates and times can be stored in many different days. Some use epoch as a date reference (January 1, 1970). In Python, you can use the time module. 

In [16]:
import datetime as dt
import time as tm

In [17]:
tm.time()

1615835900.8351734

In [18]:
# today's date (appears to be UTC)
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2021-03-15 19:18:20.844589


In [19]:
# year, month, etc.
print(dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second)

2021 3 15 19 18 20


In [20]:
# time shifts
delta = dt.timedelta(days=100)
print(delta)

today = dt.date.today()
print(today + delta)

100 days, 0:00:00
2021-06-23


In [21]:
print(today > today-delta)

True


## Advanced Python Objects, map()

Video: https://www.coursera.org/learn/python-data-analysis/lecture/PeW28/advanced-python-objects-map

In [22]:
class Person:
  department = 'School of Information'

  def set_name(self, new_name):
    self.name = new_name
  def set_location(self, new_location):
    self.location = new_location

peter = Person()
peter.set_name = 'Peter'
peter.set_location = 'Canada'
print(peter.set_name, peter.set_location)

Peter Canada


## Advanced Python Lambda and List Comprehensions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/AVjRT/advanced-python-lambda-and-list-comprehensions

Lambdas are used to create a temporary function.

In [23]:
my_function = lambda a, b, c : (a + b) ** c
my_function(1, 2, 3)

27

List comprehensions are an abbreviated method to created an iterable list. Are created on one line. LCs can include conditonal statements.

In [24]:
# conventional way
my_list = []
for num in range(20):
  if num % 2 == 0:
    my_list.append(num)
print(my_list)

# list comprehension way
print([n for n in range(20) if n % 2 == 0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


## Numerical Python Library (NumPy)

Video: https://www.coursera.org/learn/python-data-analysis/lecture/kAQc1/numerical-python-library-numpy



In [25]:
import numpy as np
import math

In [26]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim) # number of dimensions

[1 2 3]
1


In [27]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [28]:
print(b.shape) # length of each dimension

(2, 3)


In [29]:
print(b.dtype) # what types of variables

int64


In [30]:
# also floats
c = np.array([2.2, 5, 1.1])
print(c.dtype.name) # same o/p as w/o .name?

float64


In [31]:
# create according to shape
d = np.zeros((2,3)) # must pass a tuple
print(d)
e = np.ones((2,3))
print(e)
f = np.random.rand(2,3) # not a tuple! 
print(f)
print(type(f))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.41637742 0.93476222 0.60884397]
 [0.00869782 0.032488   0.93720439]]
<class 'numpy.ndarray'>


In [32]:
# range of integers
f = np.arange(10, 20, 2) # 2nd parm is exclusive
print(f)
print(type(f))

[10 12 14 16 18]
<class 'numpy.ndarray'>


In [33]:
# a range of floats
np.linspace(0, 2, 15) # 15 numbers from 0 to 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [34]:
# Array Operations

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a + b
print(c)
d = a * b
print(d)

[11 22 33 44]
[ 10  40  90 160]


In [35]:
deg_f = np.array([0,-10,-5,-15,0])
deg_c = (deg_f -32) * (5/9)
%precision 2
print(deg_c)

[-17.78 -23.33 -20.56 -26.11 -17.78]


In [36]:
# Boolean expressions on NP arrays
deg_c > -20

array([ True, False, False, False,  True])

In [37]:
# Matrix Manipulation
A = np.array([[1,1],[0,1]]) 
B = np.array([[2,0],[3,4]])
print(A * B)
# Matrix Product - Note the '@'
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [38]:
# Video completed to 8:07 only

## Manipulating Text with Regular Expression

Video: https://www.coursera.org/learn/python-data-analysis/lecture/aSuH7/manipulating-text-with-regular-expression

AKA Regex. Pattern matching. Returns chunks of text. Why use? To check if pattern exists, or return instances of text, or clean up data. 

## Regular Expression Operations Documentation

See https://docs.python.org/3/library/re.html

## Regular Expressions Debugging

See https://regex101.com/

# Experiments

In [39]:
# Marquees are back! 😊
%%html
<marquee style='width: 50%; color: Green;'>Welcome to Tutorialspoint!</marquee>