<a href="https://colab.research.google.com/github/pbeens/ICS-Computer-Studies/blob/master/Coursera_Introduction_to_Data_Science_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

Outline: https://www.coursera.org/learn/python-data-analysis/home/week/1

Forum: https://www.coursera.org/learn/python-data-analysis/discussions/weeks/1

## Introduction to Specialization

Video: https://www.coursera.org/learn/python-data-analysis/lecture/TPrDp/introduction-to-specialization

- Basic Python
- Pandas
- Advanced Querying and Manipulation
- Basic statistical analysis

## Introduction to the Course

Video: https://www.coursera.org/learn/python-data-analysis/lecture/MIvLe/introduction-to-the-course

- Data manipulation
- Pandas library, defacto standard
- Tutorial-style videos, using Jupyter
- Strategy for learning: take your own notes using Jupyter

## Syllabus

Link: https://www.coursera.org/learn/python-data-analysis/supplement/DNjE6/syllabus

- Prerequisites
- Grading and assignments
- Code of Conduct
- Working offline
- Accessibility
- Help!

## Notice for Auditing Learners: Assignment Submission

Can't submit assignments unless you are a verified (paid?) learner. A link is available to pursue this path.

## The Coursera Jupyter Notebook System

Video: https://www.coursera.org/learn/python-data-analysis/lecture/nWh1K/the-coursera-jupyter-notebook-system

- code cells and markdown cells
- code cells retain what they did in previous cells.
- Kernal/Runtime > Interrupt to stop a running process or infinite loop


## Your Personal Jupyter Notebook Workspace

Link: https://www.coursera.org/learn/python-data-analysis/ungradedLab/33VUU/your-personal-jupyter-notebook-workspace

## Week 1 Textbook Reading Assignment

Link: https://www.coursera.org/learn/python-data-analysis/supplement/fP74v/week-1-textbook-reading-assignment

- Chapter Two: Python Language Basics, IPython, and Jupyter Notebooks
- Chapter Three: Built-In Data Structures, Functions, and Files
- Chapter 4: NumPy Basics: Arrays and Vectorized Computation
- Appendix A: Advanced NumPy (optional)

### Magic Commands

In [1]:
# Jupyter has magic commands!
import numpy as np
%timeit a = np.random.randn(100, 100)

# magic commands can be assigned to variables
foo = %pwd
print(f'pwd: {foo}')

1000 loops, best of 5: 414 µs per loop
pwd: /content


- %quickref
- %magic
- %debug
- %hist
%pdb
%paste
%cpaste
%reset
%page OBJECT %run script.py %prun statement %time statement %timeit statement
%who, %who_ls, %whos 
%xdel variable


In [2]:
# May be useful later...
%matplotlib inline

## 50 years of Data Science, David Donoho (Optional)

Link: http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf

## Python Functions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/v7PKy/python-functions

High-level, interpretted language. Often used interactively, especially in Jupyter. Dynamically-typed, meaning variables are not declared as a specific type. 

Jupyter is stateful, meaning it retains values run in previous cells. 

A function returns None if not specified. 

### Examples Demo'd

In [3]:
x = 1
y = 2
x + y

3

In [4]:
x

1

In [5]:
# a function, with optional 3rd parameter
def add_numbers(x, y, z=None):
  if (z == None):
    return x + y
  else:
    return x + y + z

print(add_numbers(2, 4, 2))
print(add_numbers(2, 4))

8
6


## Python Types and Sequences

Video: https://www.coursera.org/learn/python-data-analysis/lecture/fZ466/python-types-and-sequences

`type()` shows which type a variable is

Tuple is immutable (cannot be changed). Created with parentheses. 

Lists are mutable and created with brackets. `append()` lets you add items to the list.

Lists and tuples are iterable types, typically using a `for` loop. Can be accessed via an index. Can be accessed via slicing. 

In [6]:
x = (1, 'a', 2, 'b')
print(type(x))
x = [1, 'a', 2, 'b']
print(type(x))
x.append(3.3)
print(x)
for item in x:
  print(item)
print(len(x))
print('a' in x)
print(x[0], x[0:1], x[0:2], x[:2], x[-2:])

<class 'tuple'>
<class 'list'>
[1, 'a', 2, 'b', 3.3]
1
a
2
b
3.3
5
True
1 [1] [1, 'a'] [1, 'a'] ['b', 3.3]


Strings can be split:

In [7]:
items = 'A B C D'.split()
print(items)

['A', 'B', 'C', 'D']


Dictionaries

In [8]:
# example from https://www.w3schools.com/python/python_dictionaries.asp
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for spec, data in thisdict.items():
  print(spec, data)

brand Ford
model Mustang
year 1964


In [9]:
for data in thisdict.values():
  print(data)

Ford
Mustang
1964


In [10]:
for key in thisdict.keys():
  print(key)

brand
model
year


Multiple assignments can be done at once.

In [11]:
a, b, c = 1, "abc", [4, 5]
print(a)
print(b)
print(c)

1
abc
[4, 5]


## Python More on Strings

Video: https://www.coursera.org/learn/python-data-analysis/lecture/HPh3O/python-more-on-strings

Strings are Unicode-based. They used to be based on ASCII which was too limited. UTF solves this problem by allowing over a million characters. 

Python allows placeholders for variables when concatenating strings. The video covers `format()` but we can now use f-strings.

## Python Demonstration: Reading and Writing CSV files

Video: https://www.coursera.org/learn/python-data-analysis/lecture/ktRTE/python-demonstration-reading-and-writing-csv-files



In [12]:
# This block will let you upload a file from your local computer.
# Instead, we will clone a GitHub repository, in the next cell.
import csv
# mpg.csv
from google.colab import files
# uploaded = files.upload() # Use GitHub clone instead!

In [13]:
!git clone https://github.com/pbeens/Coursera-Introduction-to-Data-Science-with-Python.git

Cloning into 'Coursera-Introduction-to-Data-Science-with-Python'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 117 (delta 20), reused 42 (delta 9), pack-reused 0
Receiving objects: 100% (117/117), 11.65 MiB | 10.38 MiB/s, done.
Resolving deltas: 100% (20/20), done.


In [14]:
# Testing another way to get a file from online
import urllib.request
url = 'https://gist.githubusercontent.com/pbeens/09530d2a47a926940216b971ecdce369/raw/50f899381a90c94cfd130dc41599fb3d51a2d372/mpg.csv'
urllib.request.urlretrieve(url, "mpg.csv")

('mpg.csv', <http.client.HTTPMessage at 0x7fa816fe0110>)

In [15]:
import csv

# %precision 2 # not working in this cell for some reason
mpg_file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/datasets/mpg.csv'
with open(mpg_file) as csvfile:
  mpg = list(csv.DictReader(csvfile))

# let's look at the first entry
print(mpg[:1])

# how many entries?
print(len(mpg))

# the keys
print(mpg[0].keys())

# avg mpg, city and highway
cty_mpg_avg = sum(float(d['cty']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{cty_mpg_avg:.2f}') # Note: %precision 2 did not work 
hwy_mpg_avg = sum(float(d['hwy']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{hwy_mpg_avg:.2f}')

# cylinder mpg study
cylinders = set(d['cyl'] for d in mpg) # create set of # of cylinders
print(cylinders)

cty_mpg_by_cyl = []
for c in cylinders:
  sum_mpg = 0
  cyl_type_count = 0
  for d in mpg:
    if d['cyl'] == c:
      sum_mpg += float(d['cty'])
      cyl_type_count += 1
  cty_mpg_by_cyl.append((c, round(sum_mpg / cyl_type_count, 2)))
print(sorted(cty_mpg_by_cyl))

# vehicle class study
vehicle_classes = set(d['class'] for d in mpg)
print(vehicle_classes)

hwy_mpg_by_class = []
for vc in vehicle_classes:
  sum_mpg = 0
  vehicle_class_count = 0
  for d in mpg:
    if d['class'] == vc:
      sum_mpg += float(d['hwy'])
      vehicle_class_count += 1
  hwy_mpg_by_class.append((vc, round(sum_mpg / vehicle_class_count)))
print(sorted(hwy_mpg_by_class))


[OrderedDict([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])]
234
odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])
16.86
23.44
{'4', '5', '6', '8'}
[('4', 21.01), ('5', 20.5), ('6', 16.22), ('8', 12.57)]
{'pickup', 'suv', 'midsize', 'subcompact', 'compact', '2seater', 'minivan'}
[('2seater', 25), ('compact', 28), ('midsize', 27), ('minivan', 22), ('pickup', 17), ('subcompact', 28), ('suv', 18)]


## Python Dates and Times

Video: https://www.coursera.org/learn/python-data-analysis/lecture/Fpybh/python-dates-and-times

Dates and times can be stored in many different days. Some use epoch as a date reference (January 1, 1970). In Python, you can use the time module. 

In [16]:
import datetime as dt
import time as tm

In [17]:
tm.time()

1616339917.3937685

In [18]:
# today's date (appears to be UTC)
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2021-03-21 15:18:37.404855


In [19]:
# year, month, etc.
print(dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second)

2021 3 21 15 18 37


In [20]:
# time shifts
delta = dt.timedelta(days=100)
print(delta)

today = dt.date.today()
print(today + delta)

100 days, 0:00:00
2021-06-29


In [21]:
print(today > today-delta)

True


## Advanced Python Objects, map()

Video: https://www.coursera.org/learn/python-data-analysis/lecture/PeW28/advanced-python-objects-map

In [22]:
class Person:
  department = 'School of Information'

  def set_name(self, new_name):
    self.name = new_name
  def set_location(self, new_location):
    self.location = new_location

peter = Person()
peter.set_name = 'Peter'
peter.set_location = 'Canada'
print(peter.set_name, peter.set_location)

Peter Canada


## Advanced Python Lambda and List Comprehensions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/AVjRT/advanced-python-lambda-and-list-comprehensions

Lambdas are used to create a temporary function.

In [23]:
my_function = lambda a, b, c : (a + b) ** c
my_function(1, 2, 3)

27

List comprehensions are an abbreviated method to created an iterable list. Are created on one line. LCs can include conditonal statements.

In [24]:
# conventional way
my_list = []
for num in range(20):
  if num % 2 == 0:
    my_list.append(num)
print(my_list)

# list comprehension way
print([n for n in range(20) if n % 2 == 0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


## Numerical Python Library (NumPy)

Video: https://www.coursera.org/learn/python-data-analysis/lecture/kAQc1/numerical-python-library-numpy



In [25]:
import numpy as np
import math

In [26]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim) # number of dimensions

[1 2 3]
1


In [27]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [28]:
print(b.shape) # length of each dimension

(2, 3)


In [29]:
print(b.dtype) # what types of variables

int64


In [30]:
# also floats
c = np.array([2.2, 5, 1.1])
print(c.dtype.name) # same o/p as w/o .name?

float64


In [31]:
# create according to shape
d = np.zeros((2,3)) # must pass a tuple
print(d)
e = np.ones((2,3))
print(e)
f = np.random.rand(2,3) # not a tuple! 
print(f)
print(type(f))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.90557773 0.8527093  0.87888981]
 [0.12842647 0.84215436 0.18490588]]
<class 'numpy.ndarray'>


In [32]:
# range of integers
f = np.arange(10, 20, 2) # 2nd parm is exclusive
print(f)
print(type(f))

[10 12 14 16 18]
<class 'numpy.ndarray'>


In [33]:
# a range of floats
np.linspace(0, 2, 15) # 15 numbers from 0 to 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [34]:
# Array Operations

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a + b
print(c)
d = a * b
print(d)

[11 22 33 44]
[ 10  40  90 160]


In [35]:
deg_f = np.array([0,-10,-5,-15,0])
deg_c = (deg_f -32) * (5/9)
%precision 2
print(deg_c)

[-17.78 -23.33 -20.56 -26.11 -17.78]


In [36]:
# Boolean expressions on NP arrays
deg_c > -20

array([ True, False, False, False,  True])

In [37]:
# Matrix Manipulation
A = np.array([[1,1],[0,1]]) 
B = np.array([[2,0],[3,4]])
print(A * B)
# Matrix Product - Note the '@'
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [38]:
# Video completed to 8:07 only

## Manipulating Text with Regular Expression

Video: https://www.coursera.org/learn/python-data-analysis/lecture/aSuH7/manipulating-text-with-regular-expression

AKA Regex. Pattern matching. Returns chunks of text. Why use? To check if pattern exists, or return instances of text, or clean up data. 

In [39]:
import re

# match() returns a boolean

### re.search()

In [40]:
# search returns a boolean

text = 'This is a good day'
if re.search('good', text):
  print('Wonderful!')
else:
  print('Alas :(')

Wonderful!


### findall() and split()

In [41]:
# findall() and split() return chunks

text = 'Amy works diligently. Amy gets good grades. Our student Amy is successful'
print(re.split('Amy', text)) # returns chunks split on 'Amy'
print(re.findall('Amy', text))
print(len(re.findall('Amy', text))) # number of occurrences

['', ' works diligently. ', ' gets good grades. Our student ', ' is successful']
['Amy', 'Amy', 'Amy']
3


### Anchors

In [42]:
# Anchors, ^ = at start, $ = at end

print(re.search('^Amy', text)) # returns a re object

<re.Match object; span=(0, 3), match='Amy'>


### Patterns and Character Classes

In [43]:
# Patterns and Character Classes

grades = 'ACAAAABCBCBAA'

print(re.findall('B', grades)) # ['B', 'B', 'B']

# [] are used for options (or)

print(re.findall('[BC]', grades)) # ['C', 'B', 'C', 'B', 'C', 'B']

print(re.findall('[A][BC]', grades)) # ['AC', 'AB']
print(re.findall('[A][B-C]', grades)) # [B-C] is the range from B-C

# | = OR

print(re.findall('BC|BA', grades)) # ['BC', 'BC', 'BA']

# A carat can be used to negate inside of a set operator

print(re.findall('[^A]', grades)) # ['C', 'B', 'C', 'B', 'C', 'B']
print(re.findall('^[^A]', grades)) # produces [] empty list (starts with A)

['B', 'B', 'B']
['C', 'B', 'C', 'B', 'C', 'B']
['AC', 'AB']
['AC', 'AB']
['BC', 'BC', 'BA']
['C', 'B', 'C', 'B', 'C', 'B']
[]


### Quantifiers

In [44]:
import re

# Quantifiers - number of times e{m,n} e=expression, m=minTimes, n=MaxTimes 

grades = 'ACAAAABCBCBAA'

# streaks of a character
print(re.findall('A{2,10}', grades)) # between 2 and 10 A's = ['AAAA', 'AA']
print(re.findall('A{1,1}A{1,1}', grades)) # ['AA', 'AA', 'AA']

# regex "consumes" strings (i.e., characters are not reused)

# watching extra space!
print(re.findall('A{2,2}', grades)) # ['AA', 'AA', 'AA']
print(re.findall('A{2, 2}', grades)) # []

# one number in braces is considered min and max

print(re.findall('A{2}', grades)) # ['AA', 'AA', 'AA']

# * = 0 times
# ? = one or more times
# + = one or more times
# \w = any pattern of number or character
# \s = any whitespace

# remember to re-read in GitHub repository
ferpa = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/ferpa.txt'
with open(ferpa) as file:
  wiki = file.read()

# headers in this article look like this: Overview[edit]

# -> ['Overview[edit]', 'records[edit]', 'records[edit]']
# note that brackets must be escaped
print(re.findall('[a-z|A-Z]{1,100}\[edit\]', wiki))

# equivalent of previous example (with \w) Note: [\w] = [a-z|A-Z] 
print(re.findall('[\w]{1,100}\[edit\]', wiki))

# equivalent again! (with *)
print(re.findall('[\w]*\[edit\]', wiki))

# now let's include spaces to get entire headers
print(re.findall('[\w ]*\[edit\]', wiki)) # ['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']

# Let's extract the titles, splitting on the '[' at the beginning of [edit]
print('=== Titles ===')
for title in re.findall('[\w ]*\[edit\]', wiki):
  print(re.split('[\[]', title)[0])

['AAAA', 'AA']
['AA', 'AA', 'AA']
['AA', 'AA', 'AA']
[]
['AA', 'AA', 'AA']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
=== Titles ===
Overview
Access to public records
Student medical records


### Groups

In [45]:
# Groups

# Let's improve upone the previous example by creating groups (in parentheses)
# item.groups() returns a tuple of each group item
# group(0) is the entire item, group(1) is first, etc.

print('=== Old way ===')
print(re.findall('[\w ]*\[edit\]', wiki))

print('=== item.groups() ===')
for item in re.finditer('([\w ]*)(\[edit\])', wiki):
  print(item.groups())

print('=== item.group(1) ===')
for item in re.finditer('([\w ]*)(\[edit\])', wiki):
  print(item.group(1))

# groups can be named with ?P<name> and use of groupdict()[]

print('=== named with ?P<name> ===')
for item in re.finditer('(?P<title>[\w ]*)(?P<edit_link>\[edit\])', wiki):
  print(item.groupdict()['title'])

print('=== groupdict() ===')
for item in re.finditer('(?P<title>[\w ]*)(?P<edit_link>\[edit\])', wiki):
  print(item.groupdict())

# . = single character
# /d = digit
# /s = white space

=== Old way ===
['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
=== item.groups() ===
('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')
=== item.group(1) ===
Overview
Access to public records
Student medical records
=== named with ?P<name> ===
Overview
Access to public records
Student medical records
=== groupdict() ===
{'title': 'Overview', 'edit_link': '[edit]'}
{'title': 'Access to public records', 'edit_link': '[edit]'}
{'title': 'Student medical records', 'edit_link': '[edit]'}


### Look-ahead and Look-behind (stuff to ignore)

In [46]:
# Look-ahead and Look-behind with ?=
# This example ignores [edit]

for item in re.finditer('(?P<title>[\w ]+)(?=\[edit\])', wiki):
  print(item)

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


### Example : Wikipedia Data

In [47]:
# Example : Wikipedia Data

import re

file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/buddhist.txt'
with open(file) as f:
  wiki = f.read()

# print(wiki[:1000])

pattern = """
(?P<title>.*)       # the university title
(–\ located\ in\ )  # an indicator of the location (Note: copy correct dash type!)
(?P<city>\w*)       # city the university is in
(,\ )               # separator for the state
(?P<state>\w*)      # the state the university is located in
"""

print('=== re.finditer(pattern, wiki, re.VERBOSE) ===')
for item in re.finditer(pattern, wiki, re.VERBOSE):
  print(item.groupdict())

=== re.finditer(pattern, wiki, re.VERBOSE) ===
{'title': 'Dhammakaya Open University ', 'city': 'Azusa', 'state': 'California'}
{'title': 'Dharmakirti College ', 'city': 'Tucson', 'state': 'Arizona'}
{'title': 'Dharma Realm Buddhist University ', 'city': 'Ukiah', 'state': 'California'}
{'title': 'Ewam Buddhist Institute ', 'city': 'Arlee', 'state': 'Montana'}
{'title': 'Institute of Buddhist Studies ', 'city': 'Berkeley', 'state': 'California'}
{'title': 'Maitripa College ', 'city': 'Portland', 'state': 'Oregon'}
{'title': 'University of the West ', 'city': 'Rosemead', 'state': 'California'}
{'title': 'Won Institute of Graduate Studies ', 'city': 'Glenside', 'state': 'Pennsylvania'}


### Example: New York Times and Hashtags

In [48]:
# Example: New York Times and Hashtags

file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/nytimeshealth.txt'
with open(file) as f:
  health = f.read()

print('=== health[:500] ===')
print(health[:500])

# let's grab hashtags

pattern = '#[\w\d]*(?=\s)'

print(re.findall(pattern, health))
print(set(re.findall(pattern, health))) # get rid of dupes


=== health[:500] ===
548662191340421120|Sat Dec 27 02:10:34 +0000 2014|Risks in Using Social Media to Spot Signs of Mental Distress http://nyti.ms/1rqi9I1
548579831169163265|Fri Dec 26 20:43:18 +0000 2014|RT @paula_span: The most effective nationwide diabetes prevention program you've probably never heard of:  http://newoldage.blogs.nytimes.com/2014/12/26/diabetes-prevention-that-works/
548579045269852161|Fri Dec 26 20:40:11 +0000 2014|The New Old Age Blog: Diabetes Prevention That Works http://nyti.ms/1xm7fTi
54844
['#askwell', '#pregnancy', '#Colorado', '#VegetarianThanksgiving', '#FallPrevention', '#Ebola', '#Ebola', '#ebola', '#Ebola', '#Ebola', '#EbolaHysteria', '#AskNYT', '#Ebola', '#Ebola', '#Liberia', '#Excalibur', '#ebola', '#Ebola', '#dallas', '#nobelprize2014', '#ebola', '#ebola', '#monrovia', '#ebola', '#nobelprize2014', '#ebola', '#nobelprize2014', '#Medicine', '#Ebola', '#Monrovia', '#Ebola', '#smell', '#Ebola', '#Ebola', '#Ebola', '#Monrovia', '#Ebola', '#ebola', '#monro

## Regular Expression Operations Documentation

See https://docs.python.org/3/library/re.html

## Regular Expressions Debugging

See https://regex101.com/

# Week 2: Basic Data Processing with Pandas



Week 2: https://www.coursera.org/learn/python-data-analysis/home/week/2

Discussion Forum: https://www.coursera.org/learn/python-data-analysis/discussions/weeks/2

In this week of the course you'll learn the fundamentals of one of the most important toolkits Python has for data cleaning and processing -- pandas. You'll learn how to read in data into DataFrame structures, how to query these structures, and the details about such structures are indexed.

Learning Objectives
- Demonstrate how the series class builds on top of numpy datatypes
- Remember that the series class is a numpy array
- Demonstrate the basics of how to query a series structure
- Remember the dataframe as the principle data science structure
- Define the various features of a dataframe
- Demonstrate what an axis is in relation to dataframes
- Demonstrate the difference between the series and dataframe classes
- Create and use pandas DataFrames to represent raw data

## Week 2 Reading Assignments

Course Textbook
[Python for Data Analysis](https://wesmckinney.com/pages/book.html) by Wes McKinney (O’Reilly). Copyright 2017 Wes McKinney, 978-1-491-95766-0.

- Chapter Five: Getting started with pandas
- Chapter Seven: Data Cleaning and Preparation

## Introduction to Pandas

Video: https://www.coursera.org/learn/python-data-analysis/lecture/khJPQ/introduction-to-pandas

Stack Overflow Reference: https://stackoverflow.com/questions/tagged/pandas

Open Source, created in 2008 by Wes McKinney (the same author as the referece book)

See https://planetpython.org/ 



## The Series Data Structure


Video: https://www.coursera.org/learn/python-data-analysis/lecture/lhVO7/the-series-data-structure



In [49]:
import pandas as pd

students = ['Alice', 'Jack', 'Molly']
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [50]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [51]:
students = ['Alice', 'Jack', None]
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [52]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [53]:
import numpy as np

print(np.nan == None) # False
print(np.nan == np.nan) # False (what?!! You can't do an equiality test to NaN...)
print(np.isnan(np.nan)) # True (this works this way)

False
False
True


In [54]:
import pandas as pd

student_scores = {'Alice': 'Physics',
                  'Jack': 'Chemistry',
                  'MOlly': 'English'}

s = pd.Series(student_scores)
print(s)

Alice      Physics
Jack     Chemistry
MOlly      English
dtype: object


In [55]:
print(s.index)

Index(['Alice', 'Jack', 'MOlly'], dtype='object')


In [56]:
students = [('Alice', 'Brown'), ('Jack', 'White'), ('Molly', 'Green')] # list of Tuples
print(pd.Series(students))

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object


In [57]:
s = pd.Series(['Physics', 'Chemistry', 'English'], index = ['Alice', 'Jack', 'Molly'])
print(s)

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object


In [58]:
# What happens when series doesn't agree with index? NaN
student_scores = {'Alice': 'Physics',
                  'Jack': 'Chemistry',
                  'Molly': 'English'}
s = pd.Series(student_scores, index = ['Alice', 'Molly', 'Sam'])
print(s)

Alice    Physics
Molly    English
Sam          NaN
dtype: object


## Querying a Series

Video: https://www.coursera.org/learn/python-data-analysis/lecture/3Fk9W/querying-a-series

Can query by index position (iloc) or index label (loc).

What does the term “broadcasting” mean in Pandas documentation?
https://stackoverflow.com/questions/29954263/what-does-the-term-broadcasting-mean-in-pandas-documentation


In [59]:
import pandas as pd

student_classes = pd.Series(['Physics', 'Chemistry', 'English', 'History'], index = ['Alice', 'Jack', 'Molly', 'Sam'])
s = pd.Series(student_classes)
print(s)


Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object


In [60]:
print(s.iloc[3]) # index #3

History


In [61]:
print(s.loc['Molly']) # index 'Molly'

English


In [62]:
print(s[0])     # both work! 
print(s['Alice'])

Physics
Physics


In [63]:
class_code = {99: 'Physics',
              100: 'Chemistry',
              101: 'English',
              102: 'History'}
# print(class_code[0]) # won't work in this case because indices are numbers
print(class_code[99]) # works

Physics


In [64]:
# iterate over list - long way

grades = pd.Series([90, 80, 70, 60])

total = 0
for grade in grades:
  total += grade
print(total/len(grades))

75.0


In [65]:
# iterate over list - better way

import numpy as np

total = np.sum(grades)
print(total / len(grades))

75.0


In [66]:
# Let's set up to time the different methods to show which is faster

numbers = pd.Series(np.random.randint(0, 1000, 10000))
print(len(numbers))
print(numbers.head())

10000
0     34
1    586
2    333
3     48
4    585
dtype: int64


In [67]:
%%timeit -n100

# iterative way

total = 0
for number in numbers:
  total += number
total / len(numbers)

100 loops, best of 5: 1.29 ms per loop


In [68]:
%%timeit -n100

# better way - way faster! (uses numpy broadcasting)

total = np.sum(numbers)
total/len(numbers)

100 loops, best of 5: 66.3 µs per loop


In [69]:
print(numbers.head())

0     34
1    586
2    333
3     48
4    585
dtype: int64


In [70]:
# let's add 2 to all items
numbers += 2 # works fast on a np.Series! 
print(numbers.head())

0     36
1    588
2    335
3     50
4    587
dtype: int64


In [71]:
%%timeit n=10

# slow iterative approach

s = pd.Series(np.random.randint(0, 1000, 10000))
for label, value in s.iteritems():
  s.loc[label] = value + 2

1 loop, best of 5: 482 ms per loop


In [72]:
%%timeit -n10

# waaaay faster way!

s = pd.Series(np.random.randint(0, 1000, 10000))
s += 2


10 loops, best of 5: 320 µs per loop


In [73]:
s = pd.Series([1,2,3])
s.loc['History'] = 102 # add new index. Not a problem
print(s)

0            1
1            2
2            3
History    102
dtype: int64


In [74]:
# unique indexes
students_classes = pd.Series({'Alice': 'Physics',
                              'Jack': 'Chemistry',
                              'Molly': 'English',
                              'Sam': 'History'})
print(student_classes)

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object


In [75]:
# identtical indexes
kelly_classes = pd.Series(['Philosophy', 'Arts', 'Math'], index = ['Kelly', 'Kelly', 'Kelly'])
print(kelly_classes)

Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object


In [76]:
# merge the dissimilar Series - not a problem!
# Pandas always does its best to merge series
all_students_classes = students_classes.append(kelly_classes)
print(all_students_classes)

Alice       Physics
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly          Arts
Kelly          Math
dtype: object


## DataFrame Data Structure


Video: https://www.coursera.org/learn/python-data-analysis/lecture/J8MzB/dataframe-data-structure

Dataframes are the heart of the panda library. A 2-dimensional series, with an index and multiple columns of data.

In [77]:
import pandas as pd

# let's set up some data to use (multiple dictionaries)

record1 = pd.Series({'Name': 'Alice',
                     'Class': 'Physics',
                     'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                     'Class': 'Chemistry',
                     'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                     'Class': 'Biology',
                     'Score': 90})

df = pd.DataFrame([record1, record2, record3], 
                  index = ['school1', 'school2', 'school3'])

In [78]:
df.head()

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school3  Helen    Biology     90

In [79]:
# Another way to enter the data (list of dictionaries)

students = [{'Name': 'Alice',
                     'Class': 'Physics',
                     'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
                     'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]

df = pd.DataFrame(students, index = ['school1', 'school2', 'school1']) # two school 1's
df.head()

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [80]:
# accessing by index

df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [81]:
# what type is the data?

print(type(df.loc['school2'])) # one record, so it's a Series
print(type(df.loc['school1'])) # two records, do it's a DataFrame

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [82]:
df.loc['school1'] 

Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [83]:
# only return specific data, not entire record

df.loc['school1', 'Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [84]:
# how to transpose the data

df.T

school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [85]:
# What if we want all the contents of a column? Transpose first....

df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [86]:
# but this does the same...! (why transpose then????)
# note: .loc() not used to get the columnar data

df['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [87]:
# Columnar selection returns a Series, not a DataFrame

type(df['Name'])

# Just use type() to check what something returns

pandas.core.series.Series

In [88]:
# .loc() can use slicing

df.loc[:,['Name', 'Score']]

Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [89]:
# data can be dropped

df.drop('school2')

Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [90]:
# ...but the dropped data is still there!
# (returns a copy)

df

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [91]:
# Use inpalce=True to really drop the data!
# axis=0 is a row (default), axis=1 is a column
# Using a copy of the data here

copy_df = df.copy()
copy_df.drop('Name', inplace=True, axis=1)
copy_df

Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [92]:
# A 2nd way to drop a column
# This is permanent. A copy is NOT returned.

del copy_df['Class']
copy_df

Score
school1     85
school2     82
school1     90

In [93]:
# Add a column. 

df['ClassRanking'] = None
df

Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None

## DataFrame Indexing and Loading

Video: https://www.coursera.org/learn/python-data-analysis/lecture/BLY4L/dataframe-indexing-and-loading

# Experiments

In [94]:
# Marquees are back! 😊
%%html
<marquee style='width: 50%; color: Green;'>Welcome to Tutorialspoint!</marquee>

In [95]:
import numpy as np

a = np.zeros([20,20])
b = np.ones([20,20])

print(a + b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.