<a href="https://colab.research.google.com/github/pbeens/ICS-Computer-Studies/blob/master/Coursera_Introduction_to_Data_Science_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1

Outline: https://www.coursera.org/learn/python-data-analysis/home/week/1

Forum: https://www.coursera.org/learn/python-data-analysis/discussions/weeks/1

## Introduction to Specialization

Video: https://www.coursera.org/learn/python-data-analysis/lecture/TPrDp/introduction-to-specialization

- Basic Python
- Pandas
- Advanced Querying and Manipulation
- Basic statistical analysis

## Introduction to the Course

Video: https://www.coursera.org/learn/python-data-analysis/lecture/MIvLe/introduction-to-the-course

- Data manipulation
- Pandas library, defacto standard
- Tutorial-style videos, using Jupyter
- Strategy for learning: take your own notes using Jupyter

## Syllabus

Link: https://www.coursera.org/learn/python-data-analysis/supplement/DNjE6/syllabus

- Prerequisites
- Grading and assignments
- Code of Conduct
- Working offline
- Accessibility
- Help!

## Notice for Auditing Learners: Assignment Submission

Can't submit assignments unless you are a verified (paid?) learner. A link is available to pursue this path.

## The Coursera Jupyter Notebook System

Video: https://www.coursera.org/learn/python-data-analysis/lecture/nWh1K/the-coursera-jupyter-notebook-system

- code cells and markdown cells
- code cells retain what they did in previous cells.
- Kernal/Runtime > Interrupt to stop a running process or infinite loop


## Your Personal Jupyter Notebook Workspace

Link: https://www.coursera.org/learn/python-data-analysis/ungradedLab/33VUU/your-personal-jupyter-notebook-workspace

## Week 1 Textbook Reading Assignment

Link: https://www.coursera.org/learn/python-data-analysis/supplement/fP74v/week-1-textbook-reading-assignment

- Chapter Two: Python Language Basics, IPython, and Jupyter Notebooks
- Chapter Three: Built-In Data Structures, Functions, and Files
- Chapter 4: NumPy Basics: Arrays and Vectorized Computation
- Appendix A: Advanced NumPy (optional)

### Magic Commands

In [ ]:
# Jupyter has magic commands!
import numpy as np
%timeit a = np.random.randn(100, 100)

# magic commands can be assigned to variables
foo = %pwd
print(f'pwd: {foo}')

The slowest run took 4.05 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 420 µs per loop
pwd: /content


- %quickref
- %magic
- %debug
- %hist
%pdb
%paste
%cpaste
%reset
%page OBJECT %run script.py %prun statement %time statement %timeit statement
%who, %who_ls, %whos 
%xdel variable


In [ ]:
# May be useful later...
%matplotlib inline

## 50 years of Data Science, David Donoho (Optional)

Link: http://courses.csail.mit.edu/18.337/2015/docs/50YearsDataScience.pdf

## Python Functions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/v7PKy/python-functions

High-level, interpretted language. Often used interactively, especially in Jupyter. Dynamically-typed, meaning variables are not declared as a specific type. 

Jupyter is stateful, meaning it retains values run in previous cells. 

A function returns None if not specified. 

### Examples Demo'd

In [ ]:
x = 1
y = 2
x + y

3

In [ ]:
x

1

In [ ]:
# a function, with optional 3rd parameter
def add_numbers(x, y, z=None):
  if (z == None):
    return x + y
  else:
    return x + y + z

print(add_numbers(2, 4, 2))
print(add_numbers(2, 4))

8
6


## Python Types and Sequences

Video: https://www.coursera.org/learn/python-data-analysis/lecture/fZ466/python-types-and-sequences

`type()` shows which type a variable is

Tuple is immutable (cannot be changed). Created with parentheses. 

Lists are mutable and created with brackets. `append()` lets you add items to the list.

Lists and tuples are iterable types, typically using a `for` loop. Can be accessed via an index. Can be accessed via slicing. 

In [ ]:
x = (1, 'a', 2, 'b')
print(type(x))
x = [1, 'a', 2, 'b']
print(type(x))
x.append(3.3)
print(x)
for item in x:
  print(item)
print(len(x))
print('a' in x)
print(x[0], x[0:1], x[0:2], x[:2], x[-2:])

<class 'tuple'>
<class 'list'>
[1, 'a', 2, 'b', 3.3]
1
a
2
b
3.3
5
True
1 [1] [1, 'a'] [1, 'a'] ['b', 3.3]


Strings can be split:

In [ ]:
items = 'A B C D'.split()
print(items)

['A', 'B', 'C', 'D']


Dictionaries

In [ ]:
# example from https://www.w3schools.com/python/python_dictionaries.asp
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for spec, data in thisdict.items():
  print(spec, data)

brand Ford
model Mustang
year 1964


In [ ]:
for data in thisdict.values():
  print(data)

Ford
Mustang
1964


In [ ]:
for key in thisdict.keys():
  print(key)

brand
model
year


Multiple assignments can be done at once.

In [ ]:
a, b, c = 1, "abc", [4, 5]
print(a)
print(b)
print(c)

1
abc
[4, 5]


## Python More on Strings

Video: https://www.coursera.org/learn/python-data-analysis/lecture/HPh3O/python-more-on-strings

Strings are Unicode-based. They used to be based on ASCII which was too limited. UTF solves this problem by allowing over a million characters. 

Python allows placeholders for variables when concatenating strings. The video covers `format()` but we can now use f-strings.

## Python Demonstration: Reading and Writing CSV files

Video: https://www.coursera.org/learn/python-data-analysis/lecture/ktRTE/python-demonstration-reading-and-writing-csv-files



In [ ]:
# This block will let you upload a file from your local computer.
# Instead, we will clone a GitHub repository, in the next cell.
import csv
# mpg.csv
from google.colab import files
# uploaded = files.upload() # Use GitHub clone instead!

In [ ]:
!git clone https://github.com/pbeens/Coursera-Introduction-to-Data-Science-with-Python.git

Cloning into 'Coursera-Introduction-to-Data-Science-with-Python'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 117 (delta 20), reused 42 (delta 9), pack-reused 0
Receiving objects: 100% (117/117), 11.65 MiB | 9.66 MiB/s, done.
Resolving deltas: 100% (20/20), done.


In [ ]:
# Testing another way to get a file from online
import urllib.request
url = 'https://gist.githubusercontent.com/pbeens/09530d2a47a926940216b971ecdce369/raw/50f899381a90c94cfd130dc41599fb3d51a2d372/mpg.csv'
urllib.request.urlretrieve(url, "mpg.csv")

('mpg.csv', <http.client.HTTPMessage at 0x7feaa73b7c10>)

In [ ]:
import csv

# %precision 2 # not working in this cell for some reason
mpg_file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/datasets/mpg.csv'
with open(mpg_file) as csvfile:
  mpg = list(csv.DictReader(csvfile))

# let's look at the first entry
print(mpg[:1])

# how many entries?
print(len(mpg))

# the keys
print(mpg[0].keys())

# avg mpg, city and highway
cty_mpg_avg = sum(float(d['cty']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{cty_mpg_avg:.2f}') # Note: %precision 2 did not work 
hwy_mpg_avg = sum(float(d['hwy']) for d in mpg) / len(mpg) # uses list comprehension
print(f'{hwy_mpg_avg:.2f}')

# cylinder mpg study
cylinders = set(d['cyl'] for d in mpg) # create set of # of cylinders
print(cylinders)

cty_mpg_by_cyl = []
for c in cylinders:
  sum_mpg = 0
  cyl_type_count = 0
  for d in mpg:
    if d['cyl'] == c:
      sum_mpg += float(d['cty'])
      cyl_type_count += 1
  cty_mpg_by_cyl.append((c, round(sum_mpg / cyl_type_count, 2)))
print(sorted(cty_mpg_by_cyl))

# vehicle class study
vehicle_classes = set(d['class'] for d in mpg)
print(vehicle_classes)

hwy_mpg_by_class = []
for vc in vehicle_classes:
  sum_mpg = 0
  vehicle_class_count = 0
  for d in mpg:
    if d['class'] == vc:
      sum_mpg += float(d['hwy'])
      vehicle_class_count += 1
  hwy_mpg_by_class.append((vc, round(sum_mpg / vehicle_class_count)))
print(sorted(hwy_mpg_by_class))


[OrderedDict([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])]
234
odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])
16.86
23.44
{'8', '4', '5', '6'}
[('4', 21.01), ('5', 20.5), ('6', 16.22), ('8', 12.57)]
{'midsize', 'minivan', 'compact', '2seater', 'pickup', 'subcompact', 'suv'}
[('2seater', 25), ('compact', 28), ('midsize', 27), ('minivan', 22), ('pickup', 17), ('subcompact', 28), ('suv', 18)]


## Python Dates and Times

Video: https://www.coursera.org/learn/python-data-analysis/lecture/Fpybh/python-dates-and-times

Dates and times can be stored in many different days. Some use epoch as a date reference (January 1, 1970). In Python, you can use the time module. 

In [ ]:
import datetime as dt
import time as tm

In [ ]:
tm.time()

1615858130.658152

In [ ]:
# today's date (appears to be UTC)
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dtnow)

2021-03-16 01:28:50.677854


In [ ]:
# year, month, etc.
print(dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second)

2021 3 16 1 28 50


In [ ]:
# time shifts
delta = dt.timedelta(days=100)
print(delta)

today = dt.date.today()
print(today + delta)

100 days, 0:00:00
2021-06-24


In [ ]:
print(today > today-delta)

True


## Advanced Python Objects, map()

Video: https://www.coursera.org/learn/python-data-analysis/lecture/PeW28/advanced-python-objects-map

In [ ]:
class Person:
  department = 'School of Information'

  def set_name(self, new_name):
    self.name = new_name
  def set_location(self, new_location):
    self.location = new_location

peter = Person()
peter.set_name = 'Peter'
peter.set_location = 'Canada'
print(peter.set_name, peter.set_location)

Peter Canada


## Advanced Python Lambda and List Comprehensions

Video: https://www.coursera.org/learn/python-data-analysis/lecture/AVjRT/advanced-python-lambda-and-list-comprehensions

Lambdas are used to create a temporary function.

In [ ]:
my_function = lambda a, b, c : (a + b) ** c
my_function(1, 2, 3)

27

List comprehensions are an abbreviated method to created an iterable list. Are created on one line. LCs can include conditonal statements.

In [ ]:
# conventional way
my_list = []
for num in range(20):
  if num % 2 == 0:
    my_list.append(num)
print(my_list)

# list comprehension way
print([n for n in range(20) if n % 2 == 0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


## Numerical Python Library (NumPy)

Video: https://www.coursera.org/learn/python-data-analysis/lecture/kAQc1/numerical-python-library-numpy



In [ ]:
import numpy as np
import math

In [ ]:
a = np.array([1, 2, 3])
print(a)
print(a.ndim) # number of dimensions

[1 2 3]
1


In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape) # length of each dimension

(2, 3)


In [ ]:
print(b.dtype) # what types of variables

int64


In [ ]:
# also floats
c = np.array([2.2, 5, 1.1])
print(c.dtype.name) # same o/p as w/o .name?

float64


In [ ]:
# create according to shape
d = np.zeros((2,3)) # must pass a tuple
print(d)
e = np.ones((2,3))
print(e)
f = np.random.rand(2,3) # not a tuple! 
print(f)
print(type(f))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.15500822 0.30187491 0.77534023]
 [0.55720858 0.22989877 0.53152582]]
<class 'numpy.ndarray'>


In [ ]:
# range of integers
f = np.arange(10, 20, 2) # 2nd parm is exclusive
print(f)
print(type(f))

[10 12 14 16 18]
<class 'numpy.ndarray'>


In [ ]:
# a range of floats
np.linspace(0, 2, 15) # 15 numbers from 0 to 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [ ]:
# Array Operations

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a + b
print(c)
d = a * b
print(d)

[11 22 33 44]
[ 10  40  90 160]


In [ ]:
deg_f = np.array([0,-10,-5,-15,0])
deg_c = (deg_f -32) * (5/9)
%precision 2
print(deg_c)

[-17.78 -23.33 -20.56 -26.11 -17.78]


In [ ]:
# Boolean expressions on NP arrays
deg_c > -20

array([ True, False, False, False,  True])

In [ ]:
# Matrix Manipulation
A = np.array([[1,1],[0,1]]) 
B = np.array([[2,0],[3,4]])
print(A * B)
# Matrix Product - Note the '@'
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [ ]:
# Video completed to 8:07 only

## Manipulating Text with Regular Expression

Video: https://www.coursera.org/learn/python-data-analysis/lecture/aSuH7/manipulating-text-with-regular-expression

AKA Regex. Pattern matching. Returns chunks of text. Why use? To check if pattern exists, or return instances of text, or clean up data. 

In [ ]:
import re

# match() returns a boolean

### re.search()

In [ ]:
# search returns a boolean

text = 'This is a good day'
if re.search('good', text):
  print('Wonderful!')
else:
  print('Alas :(')

Wonderful!


### findall() and split()

In [ ]:
# findall() and split() return chunks

text = 'Amy works diligently. Amy gets good grades. Our student Amy is successful'
print(re.split('Amy', text)) # returns chunks split on 'Amy'
print(re.findall('Amy', text))
print(len(re.findall('Amy', text))) # number of occurrences

['', ' works diligently. ', ' gets good grades. Our student ', ' is successful']
['Amy', 'Amy', 'Amy']
3


### Anchors

In [ ]:
# Anchors, ^ = at start, $ = at end

print(re.search('^Amy', text)) # returns a re object

<re.Match object; span=(0, 3), match='Amy'>


### Patterns and Character Classes

In [ ]:
# Patterns and Character Classes

grades = 'ACAAAABCBCBAA'

print(re.findall('B', grades)) # ['B', 'B', 'B']

# [] are used for options (or)

print(re.findall('[BC]', grades)) # ['C', 'B', 'C', 'B', 'C', 'B']

print(re.findall('[A][BC]', grades)) # ['AC', 'AB']
print(re.findall('[A][B-C]', grades)) # [B-C] is the range from B-C

# | = OR

print(re.findall('BC|BA', grades)) # ['BC', 'BC', 'BA']

# A carat can be used to negate inside of a set operator

print(re.findall('[^A]', grades)) # ['C', 'B', 'C', 'B', 'C', 'B']
print(re.findall('^[^A]', grades)) # produces [] empty list (starts with A)

['B', 'B', 'B']
['C', 'B', 'C', 'B', 'C', 'B']
['AC', 'AB']
['AC', 'AB']
['BC', 'BC', 'BA']
['C', 'B', 'C', 'B', 'C', 'B']
[]


### Quantifiers

In [ ]:
import re

# Quantifiers - number of times e{m,n} e=expression, m=minTimes, n=MaxTimes 

grades = 'ACAAAABCBCBAA'

# streaks of a character
print(re.findall('A{2,10}', grades)) # between 2 and 10 A's = ['AAAA', 'AA']
print(re.findall('A{1,1}A{1,1}', grades)) # ['AA', 'AA', 'AA']

# regex "consumes" strings (i.e., characters are not reused)

# watching extra space!
print(re.findall('A{2,2}', grades)) # ['AA', 'AA', 'AA']
print(re.findall('A{2, 2}', grades)) # []

# one number in braces is considered min and max

print(re.findall('A{2}', grades)) # ['AA', 'AA', 'AA']

# * = 0 times
# ? = one or more times
# + = one or more times
# \w = any pattern of number or character
# \s = any whitespace

# remember to re-read in GitHub repository
ferpa = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/ferpa.txt'
with open(ferpa) as file:
  wiki = file.read()

# headers in this article look like this: Overview[edit]

# -> ['Overview[edit]', 'records[edit]', 'records[edit]']
# note that brackets must be escaped
print(re.findall('[a-z|A-Z]{1,100}\[edit\]', wiki))

# equivalent of previous example (with \w) Note: [\w] = [a-z|A-Z] 
print(re.findall('[\w]{1,100}\[edit\]', wiki))

# equivalent again! (with *)
print(re.findall('[\w]*\[edit\]', wiki))

# now let's include spaces to get entire headers
print(re.findall('[\w ]*\[edit\]', wiki)) # ['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']

# Let's extract the titles, splitting on the '[' at the beginning of [edit]
print('=== Titles ===')
for title in re.findall('[\w ]*\[edit\]', wiki):
  print(re.split('[\[]', title)[0])

['AAAA', 'AA']
['AA', 'AA', 'AA']
['AA', 'AA', 'AA']
[]
['AA', 'AA', 'AA']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'records[edit]', 'records[edit]']
['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
=== Titles ===
Overview
Access to public records
Student medical records


### Groups

In [ ]:
# Groups

# Let's improve upone the previous example by creating groups (in parentheses)
# item.groups() returns a tuple of each group item
# group(0) is the entire item, group(1) is first, etc.

print('=== Old way ===')
print(re.findall('[\w ]*\[edit\]', wiki))

print('=== item.groups() ===')
for item in re.finditer('([\w ]*)(\[edit\])', wiki):
  print(item.groups())

print('=== item.group(1) ===')
for item in re.finditer('([\w ]*)(\[edit\])', wiki):
  print(item.group(1))

# groups can be named with ?P<name> and use of groupdict()[]

print('=== named with ?P<name> ===')
for item in re.finditer('(?P<title>[\w ]*)(?P<edit_link>\[edit\])', wiki):
  print(item.groupdict()['title'])

print('=== groupdict() ===')
for item in re.finditer('(?P<title>[\w ]*)(?P<edit_link>\[edit\])', wiki):
  print(item.groupdict())

# . = single character
# /d = digit
# /s = white space

=== Old way ===
['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
=== item.groups() ===
('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')
=== item.group(1) ===
Overview
Access to public records
Student medical records
=== named with ?P<name> ===
Overview
Access to public records
Student medical records
=== groupdict() ===
{'title': 'Overview', 'edit_link': '[edit]'}
{'title': 'Access to public records', 'edit_link': '[edit]'}
{'title': 'Student medical records', 'edit_link': '[edit]'}


### Look-ahead and Look-behind (stuff to ignore)

In [ ]:
# Look-ahead and Look-behind with ?=
# This example ignores [edit]

for item in re.finditer('(?P<title>[\w ]+)(?=\[edit\])', wiki):
  print(item)

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


### Example : Wikipedia Data

In [ ]:
# Example : Wikipedia Data

import re

file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/buddhist.txt'
with open(file) as f:
  wiki = f.read()

# print(wiki[:1000])

pattern = """
(?P<title>.*)       # the university title
(–\ located\ in\ )  # an indicator of the location (Note: copy correct dash type!)
(?P<city>\w*)       # city the university is in
(,\ )               # separator for the state
(?P<state>\w*)      # the state the university is located in
"""

print('=== re.finditer(pattern, wiki, re.VERBOSE) ===')
for item in re.finditer(pattern, wiki, re.VERBOSE):
  print(item.groupdict())

=== re.finditer(pattern, wiki, re.VERBOSE) ===
{'title': 'Dhammakaya Open University ', 'city': 'Azusa', 'state': 'California'}
{'title': 'Dharmakirti College ', 'city': 'Tucson', 'state': 'Arizona'}
{'title': 'Dharma Realm Buddhist University ', 'city': 'Ukiah', 'state': 'California'}
{'title': 'Ewam Buddhist Institute ', 'city': 'Arlee', 'state': 'Montana'}
{'title': 'Institute of Buddhist Studies ', 'city': 'Berkeley', 'state': 'California'}
{'title': 'Maitripa College ', 'city': 'Portland', 'state': 'Oregon'}
{'title': 'University of the West ', 'city': 'Rosemead', 'state': 'California'}
{'title': 'Won Institute of Graduate Studies ', 'city': 'Glenside', 'state': 'Pennsylvania'}


### Example: New York Times and Hashtags

In [ ]:
# Example: New York Times and Hashtags

file = '/content/Coursera-Introduction-to-Data-Science-with-Python/resources/week-1/datasets/nytimeshealth.txt'
with open(file) as f:
  health = f.read()

print('=== health[:500] ===')
print(health[:500])

# let's grab hashtags

pattern = '#[\w\d]*(?=\s)'

print(re.findall(pattern, health))
print(set(re.findall(pattern, health))) # get rid of dupes


=== health[:500] ===
548662191340421120|Sat Dec 27 02:10:34 +0000 2014|Risks in Using Social Media to Spot Signs of Mental Distress http://nyti.ms/1rqi9I1
548579831169163265|Fri Dec 26 20:43:18 +0000 2014|RT @paula_span: The most effective nationwide diabetes prevention program you've probably never heard of:  http://newoldage.blogs.nytimes.com/2014/12/26/diabetes-prevention-that-works/
548579045269852161|Fri Dec 26 20:40:11 +0000 2014|The New Old Age Blog: Diabetes Prevention That Works http://nyti.ms/1xm7fTi
54844
['#askwell', '#pregnancy', '#Colorado', '#VegetarianThanksgiving', '#FallPrevention', '#Ebola', '#Ebola', '#ebola', '#Ebola', '#Ebola', '#EbolaHysteria', '#AskNYT', '#Ebola', '#Ebola', '#Liberia', '#Excalibur', '#ebola', '#Ebola', '#dallas', '#nobelprize2014', '#ebola', '#ebola', '#monrovia', '#ebola', '#nobelprize2014', '#ebola', '#nobelprize2014', '#Medicine', '#Ebola', '#Monrovia', '#Ebola', '#smell', '#Ebola', '#Ebola', '#Ebola', '#Monrovia', '#Ebola', '#ebola', '#monro

## Regular Expression Operations Documentation

See https://docs.python.org/3/library/re.html

## Regular Expressions Debugging

See https://regex101.com/

# Week 2: Basic Data Processing with Pandas



Week 2: https://www.coursera.org/learn/python-data-analysis/home/week/2

Discussion Forum: https://www.coursera.org/learn/python-data-analysis/discussions/weeks/2

In this week of the course you'll learn the fundamentals of one of the most important toolkits Python has for data cleaning and processing -- pandas. You'll learn how to read in data into DataFrame structures, how to query these structures, and the details about such structures are indexed.

Learning Objectives
- Demonstrate how the series class builds on top of numpy datatypes
- Remember that the series class is a numpy array
- Demonstrate the basics of how to query a series structure
- Remember the dataframe as the principle data science structure
- Define the various features of a dataframe
- Demonstrate what an axis is in relation to dataframes
- Demonstrate the difference between the series and dataframe classes
- Create and use pandas DataFrames to represent raw data

## Week 2 Reading Assignments

Course Textbook
[Python for Data Analysis](https://wesmckinney.com/pages/book.html) by Wes McKinney (O’Reilly). Copyright 2017 Wes McKinney, 978-1-491-95766-0.

- Chapter Five: Getting started with pandas
- Chapter Seven: Data Cleaning and Preparation

## Introduction to Pandas

Video: https://www.coursera.org/learn/python-data-analysis/lecture/khJPQ/introduction-to-pandas

Stack Overflow Reference: https://stackoverflow.com/questions/tagged/pandas

Open Source, created in 2008 by Wes McKinney (the same author as the referece book)

See https://planetpython.org/ 



## The Series Data Structure


Video: https://www.coursera.org/learn/python-data-analysis/lecture/lhVO7/the-series-data-structure



In [1]:
import pandas as pd

students = ['Alice', 'Jack', 'Molly']
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [2]:
numbers = [1, 2, 3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [3]:
students = ['Alice', 'Jack', None]
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [4]:
numbers = [1, 2, None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [ ]:
# FInished to 4:30

# Experiments

In [ ]:
# Marquees are back! 😊
%%html
<marquee style='width: 50%; color: Green;'>Welcome to Tutorialspoint!</marquee>

In [ ]:
import numpy as np

a = np.zeros([20,20])
b = np.ones([20,20])

print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.